### ISSUE TITLE
country risk taken from https://www.sanctionsmap.eu/, ignore of measures is empty

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/riksutin#22]
Currently US is listed but does not have any restrictions:

![Image](https://github.com/UniversityOfHelsinkiCS/riksutin/assets/523235/0c034de8-e2d6-4cb0-89c8-8e75a138ad91)

Ignore country if it does not have anything here:

![Image](https://github.com/UniversityOfHelsinkiCS/riksutin/assets/523235/abf1efba-ed52-41bf-86d7-569088d76e3c)

from API the correct field to look seems to be measures

![Image](https://github.com/UniversityOfHelsinkiCS/riksutin/assets/523235/eb9266eb-b16a-479c-ae2e-4ee385109a98)

So if measures is empty, igonore the country. US looks like

![Image](https://github.com/UniversityOfHelsinkiCS/riksutin/assets/523235/29348954-98e9-412c-bb96-1e88b19dc63c)

**Comment by erikao1998** [comment]
Correction: instead of looking measures,  ```has_lists``` tells if the List column is empty or not. 

For example, Montenegro looks like this in the UI:

![image](https://github.com/UniversityOfHelsinkiCS/riksutin/assets/59066641/673dfc39-f60b-480a-a96a-979a540d2d36)

the List column is empty but restrictive measures has content. In the API the data looks like this:

![image](https://github.com/UniversityOfHelsinkiCS/riksutin/assets/59066641/12374023-212a-450f-9bc1-e97958d07bec)

![image](https://github.com/UniversityOfHelsinkiCS/riksutin/assets/59066641/b07921b4-2f4e-4500-a986-8ca3383f4fed)

has_lists field is false if the List column is empty, else it's true
